automation_ref: v1.48
automation_commit: b79d282d25c04bcdb63c26e47773d3c86fdf60a3
review:
  auto: false
workflows:
  auto-rereview-request:
    enabled: false
  claude:
    enabled: false
  claude-code-review:
    enabled: false
  gemini-auto-review:
    enabled: false
  gemini-chat:
    enabled: false
  gemini-dispatch:
    enabled: false
  gemini-invoke:
    enabled: false
  gemini-issue-triage:
    enabled: false
  gemini-pr-review:
    enabled: false
  gemini-review:
    enabled: false
  gemini-scheduled-triage:
    enabled: false
  gemini-triage:
    enabled: false
  opencode:
    enabled: false
  opencode-auto-review:
    enabled: false
