name: Claude Code
run-name: jhw-review-comment-${{ github.event.comment.id || github.run_id }}

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/claude.yml@136e377eb5d3c91aff2a025d4b389c5e9d9de528
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
