name: Claude Code
run-name: jhw-review-comment-${{ github.event.comment.id || github.run_id }}

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/claude.yml@1e2dc6610c96b73bf6ec0f12ea05322f17f3122a
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
