name: Gemini Dispatch

on:
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened]
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  dispatch:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/gemini-dispatch.yml@103db505b721bd5323272ccd3a93b182d5a8086a
    with:
      repo_write_auth: github_token
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
