name: '🔀 Gemini Triage'

on:
  workflow_call:
    inputs:
      issue_number:
        type: 'string'
        description: 'Issue number'
        required: true
      issue_title:
        type: 'string'
        description: 'Issue title'
        required: true
      issue_body:
        type: 'string'
        description: 'Issue body'
        required: true
      additional_context:
        type: 'string'
        description: 'Any additional context from the request'
        required: false

jobs:
  triage:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'read'
      pull-requests: 'read'
    uses: 'jhw7500/automation/.github/workflows/gemini-triage.yml@v1.28'
    with:
      issue_number: '${{ inputs.issue_number }}'
      issue_title: '${{ inputs.issue_title }}'
      issue_body: '${{ inputs.issue_body }}'
      additional_context: '${{ inputs.additional_context }}'
    secrets: 'inherit'
